# Notes for Autograd
>
    - Torch provides 'autograd' for automatically caluculating the gradients of tensors.
    - Autograd works by keeping track of operations performed on tensors, then going backwards through those operations.
    - 'requires_grad = True' on a tensor
    - @criterion, with the 'requres_grad'
    - or at any tiem with x.requres_grad_(True)'
    <br>
    - 'torch.no_grad()' turn off gradients for a block of code
    - 'torch.set_grad_enabled(True|False) turn on or off gradietns altogether
    <br>
    - 'z.backward()' the gradients are computed with respect to some variable z

In [22]:
import torch
x = torch.randn(2,2, requires_grad = True)
print(x)

tensor([[ 0.2643,  1.0287],
        [-0.5707,  1.2247]], requires_grad=True)


In [23]:
y = x**2
print(y)

tensor([[0.0698, 1.0581],
        [0.3257, 1.4999]], grad_fn=<PowBackward0>)


In [24]:
print(y.grad_fn)
# last op was Power operation 

In [25]:
z = y.mean()
z

tensor(0.7384, grad_fn=<MeanBackward0>)

In [26]:
print(x.grad)

None


In [27]:
z.backward()
print(x.grad)
print(x/2)
# basically same vaalue btw: x.grad and x/2

tensor([[ 0.1321,  0.5143],
        [-0.2853,  0.6123]])
tensor([[ 0.1321,  0.5143],
        [-0.2853,  0.6123]], grad_fn=<DivBackward0>)
