In [4]:
import numpy as np
import torch
a  = np.random.rand(4,3)
a

array([[0.73602658, 0.35813305, 0.90088383],
       [0.90887151, 0.31731371, 0.27967135],
       [0.20489528, 0.0623012 , 0.34198337],
       [0.88357954, 0.06923606, 0.20748946]])

In [5]:
b = torch.from_numpy(a)
b
# from numpy to tensor

tensor([[0.7360, 0.3581, 0.9009],
        [0.9089, 0.3173, 0.2797],
        [0.2049, 0.0623, 0.3420],
        [0.8836, 0.0692, 0.2075]], dtype=torch.float64)

In [6]:
b.numpy()

array([[0.73602658, 0.35813305, 0.90088383],
       [0.90887151, 0.31731371, 0.27967135],
       [0.20489528, 0.0623012 , 0.34198337],
       [0.88357954, 0.06923606, 0.20748946]])

In [7]:
b.mul_(2)

tensor([[1.4721, 0.7163, 1.8018],
        [1.8177, 0.6346, 0.5593],
        [0.4098, 0.1246, 0.6840],
        [1.7672, 0.1385, 0.4150]], dtype=torch.float64)

In [9]:
a
# automatically INPLACE!
# "the memory is shared btw Numpy array and Torch tensor."

array([[1.47205317, 0.7162661 , 1.80176766],
       [1.81774303, 0.63462742, 0.5593427 ],
       [0.40979055, 0.12460241, 0.68396673],
       [1.76715907, 0.13847212, 0.41497892]])